[2023-03-15T16:08:34.083+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 01_dag_test.filter_using_variable scheduled__2022-08-09T00:00:00+00:00 [queued]>
[2023-03-15T16:08:34.206+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 01_dag_test.filter_using_variable scheduled__2022-08-09T00:00:00+00:00 [queued]>
[2023-03-15T16:08:34.210+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T16:08:34.212+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-15T16:08:34.214+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T16:08:34.278+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): filter_using_variable> on 2022-08-09 00:00:00+00:00
[2023-03-15T16:08:34.360+0000] {standard_task_runner.py:55} INFO - Started process 495 to run task
[2023-03-15T16:08:34.412+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '01_dag_test', 'filter_using_variable', 'scheduled__2022-08-09T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmp5ex65oxu']
[2023-03-15T16:08:34.468+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask filter_using_variable
[2023-03-15T16:08:34.912+0000] {task_command.py:376} INFO - Running <TaskInstance: 01_dag_test.filter_using_variable scheduled__2022-08-09T00:00:00+00:00 [running]> on host f11e2626d663
[2023-03-15T16:08:35.316+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=01_dag_test
AIRFLOW_CTX_TASK_ID=filter_using_variable
AIRFLOW_CTX_EXECUTION_DATE=2022-08-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-09T00:00:00+00:00
[2023-03-15T16:08:35.392+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-test.py", line 49, in filter_using_variable
    column_filter = Variable.get("column_filter").split(',')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable column_filter does not exist'
[2023-03-15T16:08:35.459+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=01_dag_test, task_id=filter_using_variable, execution_date=20220809T000000, start_date=20230315T160834, end_date=20230315T160835
[2023-03-15T16:08:35.603+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 29 for task filter_using_variable ('Variable column_filter does not exist'; 495)
[2023-03-15T16:08:35.812+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-03-15T16:08:36.030+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
