[2023-03-15T19:47:50.273+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 01_dag_test.connect_to_db manual__2023-03-15T19:47:49.298078+00:00 [queued]>
[2023-03-15T19:47:50.280+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 01_dag_test.connect_to_db manual__2023-03-15T19:47:49.298078+00:00 [queued]>
[2023-03-15T19:47:50.281+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T19:47:50.281+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-15T19:47:50.282+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T19:47:50.292+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): connect_to_db> on 2023-03-15 19:47:49.298078+00:00
[2023-03-15T19:47:50.302+0000] {standard_task_runner.py:55} INFO - Started process 11613 to run task
[2023-03-15T19:47:50.311+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '01_dag_test', 'connect_to_db', 'manual__2023-03-15T19:47:49.298078+00:00', '--job-id', '1180', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpoeplknil']
[2023-03-15T19:47:50.315+0000] {standard_task_runner.py:83} INFO - Job 1180: Subtask connect_to_db
[2023-03-15T19:47:50.401+0000] {task_command.py:376} INFO - Running <TaskInstance: 01_dag_test.connect_to_db manual__2023-03-15T19:47:49.298078+00:00 [running]> on host f11e2626d663
[2023-03-15T19:47:50.470+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=01_dag_test
AIRFLOW_CTX_TASK_ID=connect_to_db
AIRFLOW_CTX_EXECUTION_DATE=2023-03-15T19:47:49.298078+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-15T19:47:49.298078+00:00
[2023-03-15T19:47:50.483+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-03-15T19:47:50.491+0000] {logging_mixin.py:120} INFO - ID :1
[2023-03-15T19:47:50.492+0000] {logging_mixin.py:120} INFO - NAME :Alan Walker
[2023-03-15T19:47:50.492+0000] {logging_mixin.py:120} INFO - EMAIL :awalker@gmail.com
[2023-03-15T19:47:50.493+0000] {logging_mixin.py:120} INFO - ID :2
[2023-03-15T19:47:50.493+0000] {logging_mixin.py:120} INFO - NAME :Steve Jobs
[2023-03-15T19:47:50.494+0000] {logging_mixin.py:120} INFO - EMAIL :sjobs@gmail.com
[2023-03-15T19:47:50.494+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-test.py", line 99, in connect_to_db
    conn.commit()
NameError: name 'conn' is not defined
[2023-03-15T19:47:50.504+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=01_dag_test, task_id=connect_to_db, execution_date=20230315T194749, start_date=20230315T194750, end_date=20230315T194750
[2023-03-15T19:47:50.514+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1180 for task connect_to_db (name 'conn' is not defined; 11613)
[2023-03-15T19:47:50.559+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-03-15T19:47:50.593+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
